version: '3.8'

services:
        php:
                build:
                        context: .
                volumes:
                        - ./src/:/var/www/html
        web:
                image: nginx:1.17
                working_dir: /var/www/html
                volumes:
                        - ./src/:/var/www/html
                        - .docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf
                ports:
                        - "80:80"
        node:
                image: node:16
                user: node
                working_dir: /assets
                volumes:
                        - ./src:/assets
                command: npm run watch

        db:
                image: mariadb:10.6
                environment:
                        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
                        MYSQL_ROOT_HOST: "%"
                        MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
                        MYSQL_DATABASE: "${DB_DATABASE}"
                        MYSQL_USER: "${DB_USERNAME}"
                        MYSQL_PASSWORD: "${DB_PASSWORD}"
                volumes:
                        - mysqldata:/var/lib/mysql
        redis:
                image: redis
                volumes:
                        - redisdata:/data
        supervisor:
                build:
                        context: .
                        dockerfile: .docker/supervisord/Dockerfile
                volumes:
                        - ./src:/var/www/html
volumes:
        mysqldata:
        redisdata:
